package core

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// PipelineType represents the type of pipeline to create
type PipelineType int

const (
	PipelineGeneric PipelineType = iota
	PipelinePandasIngestion
	PipelineAPIIngestion
	PipelineCSVIngestion
)

// PipelineConfig holds configuration for a new pipeline
type PipelineConfig struct {
	Name         string
	Description  string
	Schedule     string
	PipelineType PipelineType
	TableName    string
	Tags         string
}

// DefaultPipelineConfig returns defaults for a new pipeline
func DefaultPipelineConfig() PipelineConfig {
	return PipelineConfig{
		Name:         "my_pipeline",
		Description:  "A new data pipeline",
		Schedule:     "None",
		PipelineType: PipelineGeneric,
		TableName:    "my_table",
		Tags:         "superflowsql",
	}
}

// AddPipeline creates a new pipeline DAG file in the project
func AddPipeline(config PipelineConfig, projectDir string) error {
	dagsDir := filepath.Join(projectDir, "dags")

	// Ensure dags directory exists
	if err := os.MkdirAll(dagsDir, 0755); err != nil {
		return fmt.Errorf("failed to create dags directory: %w", err)
	}

	// Generate the DAG file
	fileName := fmt.Sprintf("%s.py", sanitizeName(config.Name))
	filePath := filepath.Join(dagsDir, fileName)

	// Check if file already exists
	if _, err := os.Stat(filePath); err == nil {
		return fmt.Errorf("pipeline '%s' already exists at %s", config.Name, filePath)
	}

	var tmplContent string
	switch config.PipelineType {
	case PipelineGeneric:
		tmplContent = genericPipelineTemplate
	case PipelinePandasIngestion:
		tmplContent = pandasPipelineTemplate
	case PipelineAPIIngestion:
		tmplContent = apiPipelineTemplate
	case PipelineCSVIngestion:
		tmplContent = csvPipelineTemplate
	default:
		tmplContent = genericPipelineTemplate
	}

	funcMap := template.FuncMap{
		"lower": strings.ToLower,
	}

	tmpl, err := template.New("pipeline").Funcs(funcMap).Parse(tmplContent)
	if err != nil {
		return fmt.Errorf("template parse error: %w", err)
	}

	f, err := os.Create(filePath)
	if err != nil {
		return fmt.Errorf("file create error: %w", err)
	}
	defer f.Close()

	return tmpl.Execute(f, config)
}

func sanitizeName(name string) string {
	name = strings.ToLower(name)
	name = strings.ReplaceAll(name, " ", "_")
	name = strings.ReplaceAll(name, "-", "_")
	return name
}

// Pipeline templates

var genericPipelineTemplate = `"""
{{.Description}}
Generated by SuperFlowSQL CLI
"""
from __future__ import annotations

import pendulum
from airflow.models.dag import DAG
from airflow.operators.bash import BashOperator
from airflow.operators.python import PythonOperator


default_args = {
    "owner": "superflowsql",
    "depends_on_past": False,
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 1,
}


def process_data(**kwargs):
    """Main processing logic - customize this function."""
    print("Processing data for pipeline: {{.Name}}")
    # Add your processing logic here
    return "success"


with DAG(
    dag_id="{{.Name}}",
    start_date=pendulum.datetime(2024, 1, 1, tz="UTC"),
    schedule={{.Schedule}},
    catchup=False,
    default_args=default_args,
    tags=[{{.Tags}}],
    doc_md=__doc__,
) as dag:

    start = BashOperator(
        task_id="start",
        bash_command='echo "Starting {{.Name}}"',
    )

    process = PythonOperator(
        task_id="process",
        python_callable=process_data,
    )

    finish = BashOperator(
        task_id="finish",
        bash_command='echo "Pipeline {{.Name}} completed"',
    )

    start >> process >> finish
`

var pandasPipelineTemplate = `"""
{{.Description}}
Pandas data ingestion pipeline - Generated by SuperFlowSQL CLI
"""
from __future__ import annotations

import pendulum
import pandas as pd
import numpy as np
from airflow.decorators import dag, task
from airflow.providers.postgres.hooks.postgres import PostgresHook
from sqlalchemy import create_engine


TABLE_NAME = "{{.TableName}}"
POSTGRES_CONN_ID = "postgres_default"


@dag(
    dag_id="{{.Name}}",
    start_date=pendulum.datetime(2024, 1, 1, tz="UTC"),
    schedule={{.Schedule}},
    catchup=False,
    tags=[{{.Tags}}],
    doc_md=__doc__,
)
def pipeline():
    """{{.Description}}"""

    @task
    def extract_and_load():
        """Extract data and load into PostgreSQL."""
        # Customize your data extraction logic here
        data = {
            'id': np.arange(1, 101),
            'value': np.random.random(100),
            'category': np.random.choice(['A', 'B', 'C'], size=100),
            'created_at': pd.Timestamp.now(),
        }
        df = pd.DataFrame(data)
        print(f"DataFrame created: {len(df)} rows")

        pg_hook = PostgresHook(postgres_conn_id=POSTGRES_CONN_ID)
        conn = pg_hook.get_connection(POSTGRES_CONN_ID)
        conn_uri = f"postgresql+psycopg2://{conn.login}:{conn.password}@{conn.host}:{conn.port}/{conn.schema}"
        engine = create_engine(conn_uri)

        df.to_sql(name=TABLE_NAME, con=engine, if_exists='replace', index=False)
        print(f"Loaded {len(df)} rows into {TABLE_NAME}")

    @task
    def verify():
        """Verify data was loaded."""
        pg_hook = PostgresHook(postgres_conn_id=POSTGRES_CONN_ID)
        count = pg_hook.get_first(f"SELECT COUNT(*) FROM {TABLE_NAME}")[0]
        print(f"Table {TABLE_NAME} has {count} rows")
        assert count > 0, "No data loaded!"

    extract_and_load() >> verify()


pipeline()
`

var apiPipelineTemplate = `"""
{{.Description}}
API data ingestion pipeline - Generated by SuperFlowSQL CLI
"""
from __future__ import annotations

import pendulum
import pandas as pd
import requests
from airflow.decorators import dag, task
from airflow.providers.postgres.hooks.postgres import PostgresHook
from sqlalchemy import create_engine


TABLE_NAME = "{{.TableName}}"
POSTGRES_CONN_ID = "postgres_default"
API_URL = "https://jsonplaceholder.typicode.com/posts"  # Replace with your API


@dag(
    dag_id="{{.Name}}",
    start_date=pendulum.datetime(2024, 1, 1, tz="UTC"),
    schedule={{.Schedule}},
    catchup=False,
    tags=[{{.Tags}}],
    doc_md=__doc__,
)
def pipeline():
    """{{.Description}}"""

    @task
    def fetch_from_api():
        """Fetch data from API endpoint."""
        response = requests.get(API_URL, timeout=30)
        response.raise_for_status()
        data = response.json()
        print(f"Fetched {len(data)} records from API")
        return data

    @task
    def load_to_postgres(data):
        """Load API data into PostgreSQL."""
        df = pd.DataFrame(data)
        print(f"DataFrame: {len(df)} rows, columns: {df.columns.tolist()}")

        pg_hook = PostgresHook(postgres_conn_id=POSTGRES_CONN_ID)
        conn = pg_hook.get_connection(POSTGRES_CONN_ID)
        conn_uri = f"postgresql+psycopg2://{conn.login}:{conn.password}@{conn.host}:{conn.port}/{conn.schema}"
        engine = create_engine(conn_uri)

        df.to_sql(name=TABLE_NAME, con=engine, if_exists='replace', index=False)
        print(f"Loaded {len(df)} rows into {TABLE_NAME}")

    data = fetch_from_api()
    load_to_postgres(data)


pipeline()
`

var csvPipelineTemplate = `"""
{{.Description}}
CSV data ingestion pipeline - Generated by SuperFlowSQL CLI
"""
from __future__ import annotations

import pendulum
import pandas as pd
from airflow.decorators import dag, task
from airflow.providers.postgres.hooks.postgres import PostgresHook
from sqlalchemy import create_engine


TABLE_NAME = "{{.TableName}}"
POSTGRES_CONN_ID = "postgres_default"
CSV_PATH = "/opt/airflow/dags/data/input.csv"  # Update this path


@dag(
    dag_id="{{.Name}}",
    start_date=pendulum.datetime(2024, 1, 1, tz="UTC"),
    schedule={{.Schedule}},
    catchup=False,
    tags=[{{.Tags}}],
    doc_md=__doc__,
)
def pipeline():
    """{{.Description}}"""

    @task
    def read_csv():
        """Read data from CSV file."""
        df = pd.read_csv(CSV_PATH)
        print(f"Read {len(df)} rows from {CSV_PATH}")
        print(f"Columns: {df.columns.tolist()}")
        return df.to_dict()

    @task
    def load_to_postgres(data_dict):
        """Load CSV data into PostgreSQL."""
        df = pd.DataFrame(data_dict)
        print(f"Loading {len(df)} rows into {TABLE_NAME}")

        pg_hook = PostgresHook(postgres_conn_id=POSTGRES_CONN_ID)
        conn = pg_hook.get_connection(POSTGRES_CONN_ID)
        conn_uri = f"postgresql+psycopg2://{conn.login}:{conn.password}@{conn.host}:{conn.port}/{conn.schema}"
        engine = create_engine(conn_uri)

        df.to_sql(name=TABLE_NAME, con=engine, if_exists='replace', index=False)
        print(f"Loaded {len(df)} rows into {TABLE_NAME}")

    data = read_csv()
    load_to_postgres(data)


pipeline()
`
