package core

// envTemplate is the .env file template
var envTemplate = `# ============================================
# SuperFlowSQL - Environment Configuration
# ============================================

# --- PostgreSQL ---
POSTGRES_USER={{.PostgresUser}}
POSTGRES_PASSWORD={{.PostgresPassword}}
POSTGRES_DB_AIRFLOW={{.PostgresDB}}
POSTGRES_PORT={{.PostgresPort}}
POSTGRES_HOST={{.PostgresHost}}

# --- Airflow ---
AIRFLOW_USER={{.AirflowUser}}
AIRFLOW_PASSWORD={{.AirflowPassword}}
AIRFLOW_EMAIL={{.AirflowEmail}}
AIRFLOW_PORT={{.AirflowPort}}
AIRFLOW_FERNET_KEY={{.AirflowFernetKey}}
AIRFLOW_DB_CONN=postgresql+psycopg2://{{.PostgresUser}}:{{.PostgresPassword}}@{{.PostgresHost}}:{{.PostgresPort}}/{{.PostgresDB}}

# --- PgAdmin ---
PGADMIN_EMAIL={{.PgAdminEmail}}
PGADMIN_PASSWORD={{.PgAdminPassword}}
PGADMIN_PORT={{.PgAdminPort}}

# --- Superset ---
SUPERSET_USER={{.SupersetUser}}
SUPERSET_PASSWORD={{.SupersetPassword}}
SUPERSET_EMAIL={{.SupersetEmail}}
SUPERSET_PORT={{.SupersetPort}}
SUPERSET_SECRET_KEY={{.SupersetSecretKey}}
SUPERSET_DB_CONN=postgresql+psycopg2://{{.PostgresUser}}:{{.PostgresPassword}}@{{.PostgresHost}}:{{.PostgresPort}}/{{.PostgresDB}}
`

// dockerComposeTemplate is the docker-compose.yml template
var dockerComposeTemplate = `# ======================================================
# SuperFlowSQL - Docker Compose
# Generated by superflowsql init-project
# ======================================================

services:
  # ==========================
  # POSTGRESQL
  # ==========================
  postgres:
    image: postgres:15
    container_name: {{.ProjectName}}-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_AIRFLOW}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - data_platform
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================
  # PGADMIN
  # ==========================
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: {{.ProjectName}}-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_SETUP_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - data_platform

  # ==========================
  # AIRFLOW - WEBSERVER
  # ==========================
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: {{.ProjectName}}-airflow:latest
    container_name: {{.ProjectName}}-airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: UTC
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    ports:
      - "${AIRFLOW_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - data_platform
    entrypoint: /bin/bash
    command: -c "
      airflow db init &&
      airflow users create --username ${AIRFLOW_USER} --password ${AIRFLOW_PASSWORD} --firstname Airflow --lastname Admin --role Admin --email ${AIRFLOW_EMAIL} &&
      airflow connections delete 'postgres_default' || true &&
      airflow connections add 'postgres_default'
        --conn-type 'postgres'
        --conn-login '${POSTGRES_USER}'
        --conn-password '${POSTGRES_PASSWORD}'
        --conn-host '${POSTGRES_HOST}'
        --conn-port '${POSTGRES_PORT}'
        --conn-schema '${POSTGRES_DB_AIRFLOW}' &&
      exec airflow webserver
      "

  # ==========================
  # AIRFLOW - SCHEDULER
  # ==========================
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: {{.ProjectName}}-airflow:latest
    container_name: {{.ProjectName}}-airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: UTC
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    depends_on:
      - airflow-webserver
    networks:
      - data_platform
    entrypoint: /bin/bash
    command: -c "airflow scheduler"

  # ==========================
  # SUPERSET
  # ==========================
  superset:
    image: apache/superset:3.0.2
    container_name: {{.ProjectName}}-superset
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET_DATABASE_URI: ${SUPERSET_DB_CONN}
    ports:
      - "${SUPERSET_PORT}:8088"
    volumes:
      - superset_home:/app/superset_home
      - superset_logs:/app/superset_logs
    networks:
      - data_platform
    command: >
      /bin/bash -c "superset db upgrade &&
                    superset fab create-admin --username ${SUPERSET_USER} --password ${SUPERSET_PASSWORD} --firstname Admin --lastname User --email ${SUPERSET_EMAIL} &&
                    superset init &&
                    superset run -h 0.0.0.0 -p 8088"

# ==========================
# NETWORKS & VOLUMES
# ==========================
networks:
  data_platform:

volumes:
  postgres_data:
  airflow_logs:
  airflow_plugins:
  superset_home:
  superset_logs:
`

// dockerfileAirflowTemplate is the Dockerfile.airflow template
var dockerfileAirflowTemplate = `FROM apache/airflow:2.9.1

USER root
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
`

// requirementsTemplate is the requirements.txt template
var requirementsTemplate = `# SuperFlowSQL - Python Dependencies
apache-airflow-providers-postgres
pandas
psycopg2-binary
requests
sqlalchemy
numpy
`

// initSQLTemplate is the initial PostgreSQL schema
var initSQLTemplate = `-- SuperFlowSQL - Initial Database Schema
-- This file is executed when the PostgreSQL container first starts.

CREATE TABLE IF NOT EXISTS _superflowsql_meta (
    id SERIAL PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO _superflowsql_meta (key, value) VALUES
    ('project_name', '{{.ProjectName}}'),
    ('version', '1.0.0'),
    ('created_by', 'superflowsql-cli')
ON CONFLICT (key) DO NOTHING;
`

// pgAdminServersTemplate is the PgAdmin server config template
var pgAdminServersTemplate = `{
    "Servers": {
        "1": {
            "Name": "SuperFlowSQL - PostgreSQL",
            "Group": "SuperFlowSQL Stack",
            "Port": {{.PostgresPort}},
            "Username": "{{.PostgresUser}}",
            "Host": "{{.PostgresHost}}",
            "SSLMode": "disable",
            "MaintenanceDB": "{{.PostgresDB}}"
        }
    }
}
`

// supersetConfigTemplate is the Superset config template
var supersetConfigTemplate = `# SuperFlowSQL - Superset Configuration
SQLALCHEMY_DATABASE_URI = "postgresql://{{.PostgresUser}}:{{.PostgresPassword}}@{{.PostgresHost}}:{{.PostgresPort}}/{{.PostgresDB}}"
SECRET_KEY = "{{.SupersetSecretKey}}"
`

// exampleDAGTemplate is an example Airflow DAG
var exampleDAGTemplate = `"""
SuperFlowSQL - Example Pipeline DAG
Generated by superflowsql CLI
"""
from __future__ import annotations

import pendulum
from airflow.models.dag import DAG
from airflow.operators.bash import BashOperator
from airflow.operators.python import PythonOperator


default_args = {
    "owner": "superflowsql",
    "depends_on_past": False,
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 1,
}


def hello_superflowsql(**kwargs):
    """Example Python task."""
    print("Hello from SuperFlowSQL! Your pipeline is running.")
    return "success"


with DAG(
    dag_id="superflowsql_example",
    start_date=pendulum.datetime(2024, 1, 1, tz="UTC"),
    schedule=None,
    catchup=False,
    default_args=default_args,
    tags=["superflowsql", "example"],
) as dag:

    start = BashOperator(
        task_id="start",
        bash_command='echo "Starting SuperFlowSQL pipeline"',
    )

    process = PythonOperator(
        task_id="process",
        python_callable=hello_superflowsql,
    )

    finish = BashOperator(
        task_id="finish",
        bash_command='echo "Pipeline completed successfully"',
    )

    start >> process >> finish
`
